In [38]:
import numpy as np

In [40]:
test = np.array([[2, 3, 5], [4, 6, 8]])
#for i in test: #test what is printed when calling i in an np array
    #print(i)

'''The result of this code was that I printed each list, therefore the i in an array refers to the lists. If I want to access an individual element, 
I will need to try something else'''

for list in test: #this list variable that is already defined in python should access each list
    for i in list: #I can now use i to refer to my elements in each list
        print(i)

'''The result here was that I printed each element of each list. Therefore I can use this set up to access each element of each list in an array.'''

2
3
5
4
6
8


'The result here was that I printed each element of each list. Therefore I can use this set up to access each element of each list in an array.'

In [42]:
'''1 Prime Clusters'''
arr = np.array([[2, 3, 5], [4, 6, 8], [11, 13, 17], [7, 10, 13]])

def is_prime(n): #define a function beforehand to check if a number is prime. I will use this function within my next function.
    if n < 2:
        return False
    for j in range(2, n):
        if n % j == 0: #checks whether any number before our number n is divisible into n and gives a remainder of 0. This will mean n isn't prime
            return False
    else:
        return True

#print(is_prime(18)) #Test 1
'''result is false, which is correct'''
#print(is_prime(11)) #Test2
'''returns True, also correct.'''

def containsPrimes(arr):
    new_arr = [] #initialize list to hold our prime lists. I am using a list variable instead of an array because then I can use python functions like .append()
    for list in arr:
            if any(is_prime(i) for i in list): #use the any() function to only do the result once for each list instead of multiple times
                new_arr.append(list)
    return np.array(new_arr) #turns my list into an array at the end

print(containsPrimes(arr))

'''I ended up not using the same set up that I found earlier because if I did that I would have iterated over each 
element and therefore printed each list up to 3 times. I just kept it to for list in arr and then if any(...) because 
that would only check if any of my elements were prime. Using the earlier notation would've resulted in [2, 3, 5] and [11, 13, 17] being printed
three times (they have three prime elements) and [7, 10, 13] would've been printed twice (two primes and one non-prime, 10).'''

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


"I ended up not using the same set up that I found earlier because if I did that I would have iterated over each \nelement and therefore printed each list up to 3 times. I just kept it to for list in arr and then if any(...) because \nthat would only check if any of my elements were prime. Using the earlier notation would've resulted in [2, 3, 5] and [11, 13, 17] being printed\nthree times (they have three prime elements) and [7, 10, 13] would've been printed twice (two primes and one non-prime, 10)."

In [44]:
'''2 Let's Play Checkers!'''
#2.1
def checkerboard():
    return np.zeros((8,8)) #np.zeros creates an array of zeros. Passing a tuple in this function will specify the height and width of the array.
print(checkerboard())

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [46]:
#2.2
'''def checkerboard():
    array = np.zeros((8,8))
    for row_n, list in array: #assigns a variable equal to each list in the array, which is also equal to the array's row # and iterates over it
        for col_n, i in list: #assigns a variable to each element in each list of the array, which is equal to the array's column # and iterates
            if (col_n + row_n) % 2 == 1: #checks if the sum of the row and column indices (a.k.a. the overall array index) is odd since modulus by 2 == 1 means there is a remainder which would mean an even number
                array[row_n, col_n] = 1 #set the element we found was odd equal to one
    return array
                
print(checkerboard())

This code resulted in a ValueError on the 4th line (for row_n....) because I am putting in three values, row_n, list, and array. To fix this , I will use
enumerate() function. This function will return a tuple with the index of an element and the value of said element. i. e. arr = ['apple', 'banana', 'cherry']
for index, item in enumerate(arr): print({index}, {item})
result:
{0} {'apple'}
{1} {'banana'}
{2} {'cherry'}

Also this would be wrong because I only want to modify the odd rows, not the overall array element. So I must put an if statement in each for statement.'''

def checkerboard():
    array = np.zeros((8,8))
    for row_n, list in enumerate(array): #assigns a variable equal to each list in the array, which is also equal to the array's row # and iterates over it
        if row_n % 2 == 1: #check if the row is odd
            for col_n, i in enumerate(list): #assigns a variable to each element in each list of the array, which is equal to the array's column # and iterates
                if col_n % 2 == 1: #alternate elements
                    array[row_n, col_n] = 1
    return array
                
print(checkerboard())

'''Since Python is zero indexed, this won't give me the same result as the homework file wants, but in the end I will get the same result after the next 
step. In fact I believe the homework file result for problem 2.2 should give this result since technically these are the odd rows.'''

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


"Since Python is zero indexed, this won't give me the same result as the homework file wants, but in the end I will get the same result after the next \nstep. In fact I believe the homework file result for problem 2.2 should give this result since technically these are the odd rows."

In [48]:
'''Enumerate Function'''
arr = ['apple', 'banana', 'cherry']
for index, item in enumerate(arr):
    print({index}, {item})


{0} {'apple'}
{1} {'banana'}
{2} {'cherry'}


In [50]:
#2.3
def checkerboard():
    array = np.zeros((8,8))
    for row_n, list in enumerate(array):
        if row_n % 2 == 1: 
            for col_n, i in enumerate(list): 
                if col_n % 2 == 1: 
                    array[row_n, col_n] = 1
        elif row_n % 2 == 0: #Create a secondary condition for the even rows
            for col_n, i in enumerate(list):
                if col_n % 2 == 0: #flip this to even elements to make the pattern right
                    array[row_n, col_n] = 1
    return array
print(checkerboard())

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [52]:
#2.4
def reverse_checkerboard():
    array = np.zeros((8,8))
    for row_n, list in enumerate(array):
        if row_n % 2 == 0: #Flip which index is even and odd to flip the order of the rows
            for col_n, i in enumerate(list):
                if col_n % 2 == 1:
                    array[row_n, col_n] = 1
        elif row_n % 2 == 1:
            for col_n, i in enumerate(list):
                if col_n % 2 == 0:
                    array[row_n, col_n] = 1
    return array

print(reverse_checkerboard())

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [54]:
'''3 The Expanding Universe'''

'''Here I will use the .join() function. In order to use it the syntax is "[insert character here]".join(data type). This will insert whatever
character you put in between the quotes in between each element that you are iterating over. For example, if you put a string in the function
it will insert the character in between each letter. Putting a list of strings inside will insert the character in between each string because
in that case you are iterating over elements of the list (strings) whereas in the first case you are iterating over elements of the string (letters).'''
string1 = 'galaxy'
string2 = 'clusters'
def expansion(string1, string2, x):
    universe = [] #initialize universe list
    desired_num_spaces = " " * x #define variable to specify number of spaces
    universe.append(desired_num_spaces.join(string1)) #insert the spaces times the number of spaces desired into the words of the list
    universe.append(desired_num_spaces.join(string2))
    return np.array(universe)

print(expansion(string1, string2, 3))

['g   a   l   a   x   y' 'c   l   u   s   t   e   r   s']


In [56]:
'''4 Second-Dimmest Star'''
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)

def secondDimmest(stars):
    second_smallest_vals = [] #initialize list for values
    smallest = np.inf 
    second_smallest = np.inf  #initialize smallest and second smallest at infinity so that every number is smaller than it
    for row_n, list in enumerate(stars): #perform the function on each row of my array
        for col_n, i in enumerate(list): #iterate over each element in each list
            if i < smallest:  #if a number in a list is smaller than the smallest we have found
                second_smallest = smallest #replace second smallest with the smallest
                smallest = i #then assign smallest to that number
            elif smallest < i < second_smallest: #if our number is smaller than second smallest but bigger than smallest
                second_smallest = i #assign that number to the second smallest
        second_smallest_vals.append(second_smallest) #add the second smallest value in that list to the empty list
    return np.array(second_smallest_vals) #convert list into array

print(secondDimmest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1622  606  573  573  573]
